### ISSUE TITLE
Wiki - installation guide

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/edgetx.github.io#13]
https://github.com/EdgeTX/edgetx.github.io/wiki/EdgeTX-Installation-Guide#flashing-the-edgetx-bootloader-and-firmware

> Step 7 - Select “Write”. 

This button is now "Flash Radio Firmware" ;)

**Comment by pfeerick** [comment]
Robert just pointed out that RC Model Videos has done a flashing via bootloader that is worth throwing into the install guide as part of "Install via Bootloader" instructions ;)

https://www.youtube.com/watch?v=LItyAkJlcdU

**Comment by phileville** [comment]
Updated the "Install EdgeTX with the EdgeTX flasher" with the step. Also, added the link for the new bootloader video to the installation guide.
