### ISSUE TITLE
edgetx-flasher osx version not working

### ISSUE THREAD

**Issue by ne0c0de** [EdgeTX/edgetx.github.io#14]
Hi

I just tried to flash my TX16S firmware with edtex-flasher it's giving this error:

```
Flashing Complete
Waiting for dfu-util...

dyld: Library not loaded: /Users/tormod/dfu-util/libusb-git/../build/lib/libusb-1.0.0.dylib
Referenced from: /Applications/edgetx-flasher.app/Contents/src/support/dfu-util/darwin/dfu-util
Reason: image not found
```

I guess that dfu-path was stay as hard coded as tormod user so it's can't reach my own user path on my disk

**Comment by ne0c0de** [comment]
I flashed my TX16S with OpenTX companion without any problem.

**Comment by pfeerick** [comment]
This is the wrong repository for this issue. Flasher related feedback should go in https://github.com/EdgeTX/flasher
