### ISSUE TITLE
Spannungssensor

### ISSUE THREAD

**Issue by koaxheli** [EdgeTX/edgetx.github.io#17]
In der Telemetrie Cells wird die Auswahl von Einzelzellen beim Sender Radiomaster TX16s nicht übernommen.
Anzeige von Cell Sensor wird zwar angezeigt kann aber nicht übernommen werden.

**Comment by pfeerick** [comment]
This is the wrong repository for this issue, and I believe is a duplicate of https://github.com/EdgeTX/edgetx/issues/903, .thus should be closed
