### ISSUE TITLE
Taranis QX7 cant power on in Bootloader mode after installing EdgeTX bootloader from SD card

### ISSUE THREAD

**Issue by Andrewhutchisonfpv** [EdgeTX/edgetx.github.io#24]
Having issues here, I couldn't flash Edge Tx from computer directly to Radio when it was connected so trying the SD card route. I downloaded both nightly build and v2.5 build to try this on my Taranis QX7 and had the same issue with both. Basically when I navigate to the Firmware and install Edge Tx bootloader then power off the radio, hold the two center trim buttons in and hit the power button to enter the bootloader it just powers up the radio as normal... no bootloader mode.

When I change the bootloader back to the OpenTx version I had the radio can boot up in bootloader mode.

Any idea what could be causing this issue?

**Comment by phileville** [comment]
Is this still an issue?  If so, please try again with the current release version using the steps described here: https://github.com/EdgeTX/edgetx.github.io/wiki/EdgeTX-Installation-with-the-Bootloader
