### ISSUE TITLE
Jumper T16 Multiprotocol EdgeTX Emergency Mode

### ISSUE THREAD

**Issue by DonaldHillNZ** [EdgeTX/edgetx.github.io#25]
Hi, I have been trying to upgrade my older JumperT16 Pro with EdgeTX before I move to upgrading my Radiomaster T16S to EdgeTX. However Ive run into a problem I dont seem to be able to get around. My JT16 has an Internal Module that has been updated with the latest from Pascal Langer. If I leave my models with an internal module selected I get Emergency Mode all the time. Changing the models to No Module or external module it works but of course Ive no telemetry etc etc.
Ive tried everything I can think of including reloading the firmware about 3 times and reformatting the SDCard just in case.
Going back to OpentTX works fine.
What am I missing or is there a problem with EdgeTX and the Multiprotocol Module?

**Comment by phileville** [comment]
Is this still an issue with the current EdgeTX version?  If so, please create an issue on the main EdgetTX Repository, as this repo is for the webpage.
