### ISSUE TITLE
Logo license?

### ISSUE THREAD

**Issue by Matthias84** [EdgeTX/edgetx.github.io#27]
Hi, I like to enrich Wikipedia entries with your logo. Is it available under CC?
https://www.wikidata.org/wiki/Q110264585

**Comment by Matthias84** [comment]
I see that this isn't a important issue, but can anybody plz. point me to the author / information about the logos?

**Comment by phileville** [comment]
Yes, you can use the EdgeTX logo on wikipedia entries.

**Comment by Matthias84** [comment]
So are you ok if I upload it as CC BY SA licensed with authorship EdgeTX project? Or other details?
