### ISSUE TITLE
Companion 2.6 Crashing

### ISSUE THREAD

**Issue by ammikey** [EdgeTX/edgetx.github.io#29]
When a new theme is created on a TX16S and that theme is put in the sd card contents on the PC, companion 2.6
will not start and crashes. If the theme is removed from the sd card contents on the PC Companion starts without issue.

**Comment by phileville** [comment]
I have tested this on ETX Companion 2.7 and the issue does not happen.  Please update to that version and it should fix the issue. If the problem still exists, please create an issue ticket in the EdgeTX/EdgeTX repository as this repo is for the EdgeTX website.
