### ISSUE TITLE
Flash with Mac - Waiting for dfu-util

### ISSUE THREAD

**Issue by andrewnewton** [EdgeTX/edgetx.github.io#3]
![Screen Shot 2021-06-19 at 7 57 31 am](https://user-images.githubusercontent.com/42705629/122620281-e09e1500-d0d5-11eb-8d40-126e3120e091.jpg)

Not able to flash TX16S using Mac.
Waiting for dfu-util alert.

OS Catalina

**Comment by andrewnewton** [comment]
I'll move this to flasher maybe.

**Comment by andrewnewton** [comment]
UPDATE: Successfully flashed EdgeTX from the SD card by flashing the EdgeTX boot loader then using the TX16S Write Firmware.

**Comment by Fxlr8** [comment]
Same problem on mac OS Big Sur. What should I do?
