### ISSUE TITLE
Companion 2.6 can't be connected via USB with SD card on TX16S 

### ISSUE THREAD

**Issue by Hajolotz** [EdgeTX/edgetx.github.io#31]
An USB error Message occurs from win10 when  I try to load data from the SD card of TX16s to the PC.

**Comment by phileville** [comment]
If you are still having this issue, please update to the latest released version on Companion (2.7).  I have tested it and can confirm that it does work.  If it still does not work for you then it may be an issue with your USB cable or USB driver.
