### ISSUE TITLE
No funciona el jp4in1 en la horus 12s

### ISSUE THREAD

**Issue by aeromanolete** [EdgeTX/edgetx.github.io#36]
Pues que he instalado el último firmware (Santa) y el último firm en el módulo 4in1 y no me funciona.
Que puedo hacer?

**Comment by aeromanolete** [comment]
Well, I have installed the latest firmware (Santa) and the latest firm in the 4in1 module and it doesn't work for me.
What I can do?

**Comment by diego0815** [comment]
Did you check maybe this?
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/issues/621
