### ISSUE TITLE
How do you update EdgeTX????

### ISSUE THREAD

**Issue by QUADMAN7** [EdgeTX/edgetx.github.io#38]
How do you update EdgeTX???? i have a TX16s with EdgeTX 2.5 and i want to know how to update it to 2.6.
THX for any help!

**Comment by JurikRistjouw** [comment]
This is not an issue, please close. 
To help you: For starters, read the wiki about installing edgetx.. just pretend it is a radio with opentx on it and go from there. If that is to hard to understand, please refer from updating your setup.
