### ISSUE TITLE
edge tx multi protocol module upg recommended

### ISSUE THREAD

**Issue by GleiberM** [EdgeTX/edgetx.github.io#42]
hi, my tx12 is now runnin edgetx and i noticed that is advicing me to update de multi module, do i use the same opentx newest stable update?

**Comment by Ice601** [comment]
Hello, I have the same problem on my Radiomadter TX16. Multiprotocol module wrote: We recommend to update the module. How should I do it? There is no binding to the RX. Thank you.

**Comment by phileville** [comment]
You can download the latest MPM software here:  http://downloads.multi-module.org/
How to update: https://www.multi-module.org/using-the-module/firmware-updates/update-methods

**Comment by Ice601** [comment]
Thank you. The update went smoothly. The message has disappeared. Thank you again
