### ISSUE TITLE
Flasher has NO LUA Script selections

### ISSUE THREAD

**Issue by JWKillTime** [EdgeTX/edgetx.github.io#43]
When doing SD install there is no language selection & no LUA Script selection. It was all there before i updated the Flasher to the "LATEST" version available today 02-05-22

**Comment by phileville** [comment]
Thanks for reporting this.  However, this should be in the Flasher repository so that they Devs see it.  It has also been reported in that repo, (https://github.com/EdgeTX/flasher/issues/45) so I will close this ticket since it will be addressed by the other ticket.
