### ISSUE TITLE
Can't flash ELRS firmware on R9M module with Edge TX 2.7.0 (Radiomaster TX16S), works on 2.6.0

### ISSUE THREAD

**Issue by Kaggen67** [EdgeTX/edgetx.github.io#44]
I can't flash ELRS firmware file to my FrSky R9M 2019 ACCESS module with Edge TX 2.7.0 on the Radiomaster TX16S.

I can flash the ELRS R9M bootloader without problem but not the firmware.elrs file that gets outputed from ELRS configurator.

I highlight the firmware.elrs and klick "Flash External ELRS" and it waits a couple of seconds, then i get a short beep and after two more seconds i get a "Device not responding" message.

I downgraded to Edge TX 2.6.0 and i could flash the exact same ELRS firmware file flawlessly. So it seems to be a 2.7.0 issue.

**Comment by a1j** [comment]
There is no power enabled on the expansion interface during flashing.

**Comment by pfeerick** [comment]
This was the wrong place to post this, can you please close the issue.
