### ISSUE TITLE
SD Card Error

### ISSUE THREAD

**Issue by Catiadr** [EdgeTX/edgetx.github.io#64]
I am getting an SD Card error on the activation of the first switch (Arming) and then over time I start getting an 'Inactivity Alarm'.  This may be the SD card contacts, but if not, I thought I would place a comment here for you to look into.

**Comment by phileville** [comment]
What version of the software are you using?  Do you have a sound configured to play when Arming?  If so, then there is a good chance it is an issue with the SD Card.  What radio is the for?  Earlier versions of the TX16s sometimes had issues with the SDcard bay getting loose and causing a poor connection of the SD card, causing intermittent errors.

**Comment by Catiadr** [comment]
Strangely, it only happens on a specific model.  I may try creating a new model.

**Comment by phileville** [comment]
In this case, it is most likely the model file. Please try to create a new one from scratch.
