### ISSUE TITLE
Pan and Tilt Setup not working in EdgeTx

### ISSUE THREAD

**Issue by srhassan71** [EdgeTX/edgetx.github.io#65]
I recently converted to EdgeTx 2.8 from OpenTx and my head tracking system is not working.
On my Taranis OpenTx, I have CH5 (Pan) setup as TR5 source and it works with CobraX goggles. But when I switch to TX16S running EdgeTx, exact same setup, no movement. 
Are there additional setup required?

**Comment by phileville** [comment]
No additional settings should be needed for EdgeTX.  Double check your Trainer settings in the Sys menu.

**Comment by srhassan71** [comment]
Under trainer settings, there are 4 options.
Off
Master/jack
Slave/jack
Master/multi

which one is required to be enabled?

**Comment by pfeerick** [comment]
Compare the trainer setting with the trainer settings you're using on your OpenTX radio ;) Most likely you need Master, since you want the OUTPUT from the CobraX to feed INTO the TX16s, just like how a Student/Slave radio would.
