### ISSUE TITLE
Mac version stuck on "Filtering Sound Packs" and scripts aren't downloading

### ISSUE THREAD

**Issue by SirDrSpiderpig** [EdgeTX/edgetx.github.io#69]
Trying to create an SD card and it stuck on filtering sound packs.  Been stuck on that for about an hour now and looking at activity monitor its not getting anything from the web.  

Also if I don't select any sound packs it doesn't download any of the scripts I did select.

**Comment by phileville** [comment]
What tool are you using to download soundpacks? Buddy, Flasher or Companion?

**Comment by pfeerick** [comment]
> "Filtering Sound Packs"

This sounds like Flasher
