### ISSUE TITLE
EdgeTX 2.4 User Manual

### ISSUE THREAD

**Issue by phileville** [EdgeTX/edgetx.github.io#7]
We should create a proper user manual for EdgeTX.  This will most likely be a large undertaking, but I am sure will be well appriciated by the users.

**Comment by pfeerick** [comment]
I'm thinking something more along the lines of a quickstart guide, with links to more resources also. This could be another gitbook and repo, as that makes the web ui itself, is readily searchable and has a export to pdf function also
