### ISSUE TITLE
FrSky D8 on Radiomaster TX12

### ISSUE THREAD

**Issue by aflaude** [EdgeTX/edgetx.github.io#74]
is there a protocol for FrSky D8 receiver available to add to edgeTX on radiometer TX12? Brand new radio with the latest versions of the firmware and SD card files. New to the hobby

**Comment by phileville** [comment]
Yes, if your radio has the 4-in -1 multiprotocol module, then yes it has the D8 protocol.  In Version 2.8.3 it is under FrSky D -> D8.  If you are not sure how to configure this, take a look in the user guide: https://edgetx.gitbook.io/edgetx-user-manual/b-and-w-radios/model-select/setup
