### ISSUE TITLE
Typo in EdgeTX-Installation-Guide

### ISSUE THREAD

**Issue by OneGneissGuy** [EdgeTX/edgetx.github.io#76]
There is a typo in the subheading at this url:

https://github.com/EdgeTX/edgetx.github.io/wiki/EdgeTX-Installation-Guide#updating-your-radio-frimware

The subheading reads `Updating your radio frimware`.
The subheading should read `Updating your radio firmware`.

**Comment by OneGneissGuy** [comment]
This content is in the repo wiki

**Comment by phileville** [comment]
Thank you for pointing this out. I corrected it and ran the whole page throught the spell checker again!
